model_name: distilbert-base-uncased
dataset_csv: data/IMDB_Dataset.csv
text_col: review
label_col: sentiment
seed: 42
lr: 1.0e-05
bsz: 16
epochs: 3
wd: 0.01
max_length: 256
eval_strategy: epoch
save_strategy: epoch
disable_tqdm: false
log_level: error
log_level_replica: error
logging_steps: 50
report_to:
- none
fp16: true
early_stopping: true
early_stopping_patience: 2
load_best_model_at_end: true
metric_for_best_model: accuracy
greater_is_better: true
output_dir: runs/distilbert_auto
